spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/employee_manager
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update